export const GET_TOPICS = "GET_TOPICS";
export const GET_LANGUAGES = "GET_LANGUAGES";

export const CREATE_TOPIC = "CREATE_TOPIC";

export const CREATE_LANGUAGE = "CREATE_LANGUAGE";

export const ADD_NEW_ARTICLE_TO_STORE = "ADD_NEW_ARTICLE_TO_STORE";

export const DELETE_NEW_ARTICLE_FROM_STORE = "DELETE_NEW_ARTICLE_FROM_STORE";
export const DELETE_NEW_LANGUAGE_FROM_STORE = "DELETE_NEW_LANGUAGE_FROM_STORE";
export const DELETE_NEW_TOPIC_FROM_STORE = "DELETE_NEW_TOPIC_FROM_STORE";

export const OPEN_ERROR_TOAST = "OPEN_ERROR_TOAST";

export const CLOSE_ERROR_TOAST = "CLOSE_ERROR_TOAST";
