export const SHOW_LOADER = "SHOW_ARTICLES_LOADER";
export const HIDE_LOADER = "HIDE_ARTICLES_LOADER";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const REQUEST_ARTICLES = "REQUEST_ARTICLES";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const REQUEST_LANGUAGES = "REQUEST_LANGUAGES";

export const FETCH_TOPICS = "FETCH_TOPICS";
export const REQUEST_TOPICS = "REQUEST_LANGUAGES";
