export const SHOW_ARTICLES_LOADER = "SHOW_ARTICLES_LOADER";
export const HIDE_ARTICLES_LOADER = "HIDE_ARTICLES_LOADER";

export const REQUEST_ARTICLES = "REQUEST_ARTICLES";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
